CURRENTMAPVERSION = 8

#Kinds of entities

class EntTypes():
	"""
		A class containing all kinds of entities used.
		
		Integers that are copied from AC:
		CARROT
		CLIP
		CTF_FLAG
		I_AKIMBO
		I_AMMO
		I_ARMOUR
		I_CLIPS
		I_GRENADE
		I_HEALTH
		I_HELMET
		LADDER
		LIGHT
		MAPMODEL
		MAXENTTYPES
		NOTUSED
		PICKUPS
		PLAYERSTART
		
		Lists that provide some categorization.
		PICKUPS - A list of all items that can be picked up
		ENTITIES - A list of all the entities
		TEAMED - A list of all entities that Attrs[1] describes a team
		STATIC - A list of all entities that the player doesn't interact with gameplay (except for possibly hindering/helping movement)
		
	"""
	NOTUSED     = 0
	LIGHT       = 1
	PLAYERSTART = 2
	I_CLIPS     = 3
	I_AMMO      = 4
	I_GRENADE   = 5
	I_HEALTH    = 6
	I_HELMET    = 7
	I_ARMOUR    = 8
	I_AKIMBO    = 9
	MAPMODEL    = 10
	CARROT      = 11
	LADDER      = 12
	CTF_FLAG    = 13
	SOUND       = 14
	CLIP        = 15
	PLCLIP      = 16
	MAXENTTYPES = 17
	
	PICKUPS = [I_CLIPS, I_AMMO, I_GRENADE, I_HEALTH, I_HELMET, I_ARMOUR, I_AKIMBO]
	ENTITIES = [NOTUSED, LIGHT, PLAYERSTART, I_CLIPS, I_AMMO, I_GRENADE, I_HEALTH, I_HELMET, I_ARMOUR, I_AKIMBO, MAPMODEL, CARROT, LADDER, CTF_FLAG, SOUND, CLIP, PLCLIP, MAXENTTYPES]
	
	TEAMED = [PLAYERSTART, CTF_FLAG]
	STATIC = [NOTUSED, LIGHT, MAPMODEL, CARROT, LADDER, SOUND, CLIP, PLCLIP, MAXENTTYPES]

class LightAttrs:
	"""
		Light attribute numbers.
		
		>>> lightent.attrs[LightAttrs.R] = 255
		
		RAD - Radius
		R - Red value
		G - Green value
		B - Blue value
	"""
	RAD = 0
	R = 1
	G = 2
	B = 3

class Teams():
	"""
		Team numbers as according to the map format.
		
		Contains:
		RVSF
		CLA
		FFA
	"""
	RVSF = 1
	CLA  = 0
	FFA  = 100

#Types of cubes
class CubeTypes():
	"""
		Cube types.
		SOLID and SPACE are going to be the most common ones you will run across.
		
		Types:
		SOLID - entirely solid cube [only specifies wtex]
		CORNER - half full corner of a wall
		FHF - floor heightfield using neighbour vdelta values
		CHF - idem ceiling
		SPACE - entirely empty cube
		SEMISOLID - generated by mipmapping, you shouldn't ever see this in a mapfile
	"""
	SOLID     = 0                   # entirely solid cube [only specifies wtex]
	CORNER    = 1                   # half full corner of a wall
	FHF       = 2                   # floor heightfield using neighbour vdelta values
	CHF       = 3                   # idem ceiling
	SPACE     = 4                   # entirely empty cube
	SEMISOLID = 5                   # generated by mipmapping, you shouldn't ever see this in a mapfile