MODES = [
		 "DEMO",
		 "TEAMDEATHMATCH",
		 "COOPEDIT",
		 "DEATHMATCH",
		 "SURVIVOR",
		 "TEAMSURVIVOR",
		 "CTF",
		 "PISTOLFRENZY",
		 "BOTTEAMDEATHMATCH",
		 "BOTDEATHMATCH",
		 "LASTSWISSSTANDING",
		 "ONESHOTONEKILL",
		 "TEAMONESHOTONEKILL",
		 "BOTONESHOTONEKILL",
		 "HUNTTHEFLAG",
		 "TEAMKEEPTHEFLAG",
		 "KEEPTHEFLAG",
		 "TEAMPF",
		 "TEAMLSS",
		 "BOTPISTOLFRENZY",
		 "BOTLSS",
		 "BOTTEAMSURVIVOR",
		 "BOTTEAMONESHOTONKILL",
		 "NULL",
		 ]
		 
Modes_acynm = [
		"DEMO",
		 "TDM",
		 "COOP",
		 "DM",
		 "SURV",
		 "TSURV",
		 "CTF",
		 "PF",
		 "BTDM",
		 "BDM",
		 "LSS",
		 "OSOK",
		 "TOSOK",
		 "BOSOK",
		 "HTF",
		 "TKTF",
		 "KTF",
		 "TPF",
		 "TLSS",
		 "BPF",
		 "BLSS",
		 "BTSURV",
		 "BTOSOK",
		 "NULL",
		 ]


MasterModes = ["open", "private", "match"]

#<span style="color:#02FF80;">text</span>
ColorCodes = {'0': '02FF80',
			  '1': '60A0FF',
			  '2': 'FFC040',
			  '3': 'FF4140',
			  '4': '808080',
			  '5': 'FFFFFF',
			  '6': '603000',
			  '7': '993033',
			  '8': 'C040C0',
			  '9': 'FF6600',
			  'A': 'FFB7B7',
			  'B': 'CC3333',
			  'C': '663333',
			  'D': 'F8984E',
			  'E': 'FFFFB7',
			  'F': 'CCCC33',
			  'G': '666633',
			  'H': 'CCFC58',
			  'I': 'B7FFB7',
			  'J': '33CC33',
			  'K': '336633',
			  'L': '3FFF98',
			  'M': 'B7FFFF',
			  'N': '33CCCC',
			  'O': '336666',
			  'P': '4FCCF8',
			  'Q': 'B7B7FF',
			  'R': '3333CC',
			  'S': '333366',
			  'T': 'A049FF',
			  'U': 'FFB7FF',
			  'V': 'CC33CC',
			  'W': '663366',
			  'X': 'FF01D5',
			  'Y': 'C7D1E2',
			  'Z': '323232',
}

html_escape_table = {
	"&": "&amp;",
	'"': "&quot;",
	"'": "&apos;",
	">": "&gt;",
	"<": "&lt;",
	}