#Random map generator. ie almost everything is random.
#Most comments were added months after the creation of this script. So it may be incomplete and there might stupid coding.
#The method of completing this was not very well thought out, as I just wanted something to generate a map. This is not a example of good python usage, this is an example of the PyACube module in use
import random
from macrodefs import *
try:
	#First try to import from the main installed package
	from PyACube.mapfiles.cgz import *
	from PyACube.mapfiles.consts import *
except ImportError:
	#Then assume we are in the examples folder.
	import sys; sys.path.insert(0, "..")
	from PyACube.mapfiles.cgz import *
	from PyACube.mapfiles.consts import *

randommap = ACMap(parse=False, sfactor=7, maptitle="\f3Random Map generated by python")

#Do all the cube operations
for i in range(len(randommap)):
	#Lets get the x and y coords of this square. Lets also make a quick reference to the square.
	xy = randommap.returnXY(i)
	sqr = randommap.cubelist[i]
	
	#Now, lets set our squares values, some of them random.
	sqr.floor = 0 #Make sure it is on the same level as the others.
	sqr.ftex = random.randint(1, 70) #Safe to say there are 70 textures?
	sqr.wtex = random.randint(1, 70)
	sqr.ctex = random.randint(1, 70)
	sqr.utex = random.randint(1, 70)
	sqr.floor = random.randint(0, 1)
	sqr.ceil += random.randint(-5, 15)
	
	#Lets create our walls and lights.
	if (xy[0] % 16) == 0 or (xy[1] % 16) == 0: #if it is a multiple of 16
		sqr.kind = CubeTypes.SOLID #Make it solid
		if (xy[0] % 16) == 0 and (xy[1] % 16) == 0: #add a light, stupid if statement btw.
			randommap.addEnt( EntTypes.LIGHT, xy[0], xy[1], 5, random.randint(11, 20), random.randint(80, 255), random.randint(80, 255), random.randint(80, 255))
		continue
		
	if randommap.outofBounds(xy[0], xy[1]) or randommap.badcube(xy[0], xy[1], border = 7): #if out of bounds, or a cube that will display glitching ingame
		sqr.kind = 0 #Make it solid
		continue
		

#Upon reflection, this stuff down here could be optimized and better thought out.
for i in range(4):
	#Offset is for making doorways iirc
	offset = i - 1
	for i in range(len(randommap)):
		xy = randommap.returnXY(i)
		
		xy[0] += offset
		xy[1] += offset
		
		if randommap.outofBounds(xy[0], xy[1]) or randommap.badcube(xy[0], xy[1], border = 7): #if out of bounds
			continue
			
		if ((xy[0] % 8) == 0 and not (xy[0] % 16) == 0):
			randommap.cubelist[i].kind = CubeTypes.SPACE
			
		elif ((xy[1] % 8) == 0 and not (xy[1] % 16) == 0):
			randommap.cubelist[i].kind = CubeTypes.SPACE
			
		if offset == 0:
			if ((xy[0] % 8) == 0 and not (xy[0] % 16) == 0) and ((xy[1] % 8) == 0 and not (xy[1] % 16) == 0):
				rnd = random.randint(1, 10)
				if rnd <= 6:
					rrnd = random.randint(1, 3)
					if rrnd == 1: randommap.addEnt(EntTypes.PLAYERSTART, xy[0], xy[1], 6, random.randint(1, 359), Teams.CLA, 0, 0)
					if rrnd == 2: randommap.addEnt(EntTypes.PLAYERSTART, xy[0], xy[1], 6, random.randint(1, 359), Teams.RVSF, 0, 0)
					if rrnd == 3: randommap.addEnt(EntTypes.PLAYERSTART, xy[0], xy[1], 6, random.randint(1, 359), Teams.FFA, 0, 0)
				else:
					rrnd = random.randint(1, 100)
					if random.randint(1, 4) <= 3:
						if rrnd <= 10:
							ent = EntTypes.I_ARMOUR
						elif rrnd <= 20:
							ent = EntTypes.I_HELMET
						elif rrnd <= 40:
							ent = EntTypes.I_HEALTH
						elif rrnd <= 60:
							ent = EntTypes.I_AMMO
						elif rrnd <= 80:
							ent = EntTypes.I_GRENADE
						elif rrnd <= 95:
							ent = EntTypes.I_CLIPS
						else:
							ent = EntTypes.I_AKIMBO
						randommap.addEnt(ent, xy[0], xy[1], 1, 0, 0, 0, 0)

randommap.placeShape(MACRO_R, (51, 50), includes={'floor': 2, 'ftex': 0, 'wtex': 0})
randommap.placeShape(MACRO_R, (57, 55), includes={'floor': 2, 'ftex': 0, 'wtex': 0})
randommap.placeShape(MACRO_P, (52, 67), includes={'floor': 2, 'ftex': 0, 'wtex': 0})
randommap.placeShape(MACRO_Y, (57, 72), includes={'floor': 2, 'ftex': 0, 'wtex': 0})

randommap.addEnt(EntTypes.LIGHT, 56, 59, 1, 15, 255, 0, 0)
randommap.addEnt(EntTypes.LIGHT, 56, 72, 1, 15, 255, 0, 0)

randommap.addEnt(EntTypes.CTF_FLAG, 10, 10, 1, 0, Teams.RVSF, 0,0)
randommap.addEnt(EntTypes.CTF_FLAG, 117, 117, 1, 0, Teams.CLA, 0,0)

randommap.writeCGZ("./results/ac_random.cgz")